### ISSUE TITLE
Character "^" in content will lead incorrect search result

### ISSUE THREAD

**Issue by calfzhou** [Tipue/Tipue-Search#1]
Please check [my test branch](https://github.com/calfzhou/Tipue-Search/tree/test). I added a "^" to one page text (see [this commit](https://github.com/calfzhou/Tipue-Search/commit/c9397508c882776cb0bf26cbf918adf17574ee45)), and then the search result including this page will be incorrect.

Use search query `search suggestion box jQuery plugin` in static demo to check the search result.

Here are two screenshots show the difference:

Search result if there is no "^" in content:
![image](https://f.cloud.github.com/assets/3761553/1751637/65e8c5f0-65f6-11e3-9e9a-ebf1eb073417.png)

Search result if there is "^" in content (this is bad):
![image](https://f.cloud.github.com/assets/3761553/1751639/88c1dd14-65f6-11e3-9cba-736d38416d24.png)

**Comment by Tipue** [comment]
The latest release now uses a JavaScript object and ^ is no longer a reserved character.
