### ISSUE TITLE
Why is async set to false?

### ISSUE THREAD

**Issue by d0ugal** [Tipue/Tipue-Search#13]
This was brought up in https://github.com/tomchristie/mkdocs/pull/222.

On [this line](https://github.com/Tipue/Tipue-Search/blob/master/tipuesearch/tipuesearch.js#L36), you have the following code.

    $.ajaxSetup({
        async: false
    });

This seems like a bad idea, is there a specific reason it is required?

**Comment by Tipue** [comment]
Yes, otherwise the page can load before the data. You can change this with probably no effect for smaller data sets.

**Comment by mariusGundersen** [comment]
What is the problem with the page loading before the data? The data isn't needed until the user starts typing, and it can be loaded asynchronously while the user is typing.

**Comment by Tipue** [comment]
With larger data sets it doesn't load in time. You can always change it, but it set as false as a default for safety.

**Comment by d0ugal** [comment]
It seems like we can only change it by forking Tipue, which isn't ideal.

**Comment by Tipue** [comment]
You really don't have to fork it just for your use.

**Comment by SvenDowideit** [comment]
We are using tipuesearch for http://docs.docker.com. As you can see, the search_content.json is very large, and takes ~4 seconds to load. 

During that time, the page is unresponsive, so as is, this is unworkable.

Do you have any advice for scaling tipuesearch to larger datasets?

I was originally intending to add tipuedrop to help users searching, but I'm now considering moving the json index to only be loaded on the search results page.

**Comment by mariusGundersen** [comment]
With asynchronous loading of data the common UI trick is to use a spinner to indicate to the user that something is happening. As it is now the page completely freezes until the content has loaded. This might not take very long on the small site on a desktop computer with a good Internet connection, but those are not assumptions you can make in 2015. Also, by freezing the UI while loading the search content you are prioritizing search over the content on the page, in a way claiming that the user is more likely to search for something else than to read what is on the current page.

**Comment by Tipue** [comment]
You can call a spinner by using `<div id="tipue_search_loading"></div>`. See the documentation.

**Comment by Tipue** [comment]
Okay. I'll be starting on the next release in a week or so and I'll look at changing this.

**Comment by Tipue** [comment]
Synchronous XMLHttpRequests are now deprecated on jQuery so this will change in the next release.

**Comment by osteel** [comment]
Hi Tipue,

Any update on the next release?

Cheers

**Comment by Tipue** [comment]
There'll be a new release coming in January.

**Comment by osteel** [comment]
Cool cheers :+1:

**Comment by vozd007** [comment]
Hi, it would seem that nothing new has been released to resolve these issues?
https://github.com/Tipue/Tipue-Search

**Comment by Tipue** [comment]
Yes, it has slipped somewhat, but I’ve started working on the new version and it should be finished in around a month to six weeks.

**Comment by vozd007** [comment]
Great, thanks!
