### ISSUE TITLE
Tipue and MySQL database.

### ISSUE THREAD

**Issue by JacquesMarais** [Tipue/Tipue-Search#14]
Is it possible to use a MySQL for Tipue Search results.

**Comment by Tipue** [comment]
Not at the moment, I'm afraid. It is something I'm considering for a future release.

**Comment by JacquesMarais** [comment]
Okay thanks. Its still a great library.

**Comment by JacquesMarais** [comment]
Another question, can Tipue be used with multiple JSON files?

**Comment by Tipue** [comment]
Not at the moment, no.
