### ISSUE TITLE
[Question] Setting for navigation result

### ISSUE THREAD

**Issue by lenamtl** [Tipue/Tipue-Search#15]
We can set how many result to display total.

I don't remember where to set to display or not multi-page with navigation.
And how many item to display per page.

I may have disable that, I just don't remember where and how.

I'm using the Live mode.

Thanks

**Comment by Tipue** [comment]
Set `Show` in the `.tipuesearch()` method. See [options](http://www.tipue.com/search/docs/#opt).

**Comment by lenamtl** [comment]
Yes I know 
Let say I set 'show': 7,
This is showing TOTAL 7 results  not 7 per page 
Let say if I put 50 this will display 50 results on the page (no navigation)
Like I said I maybe I have disabled the navigation to appear, so this is why I'm asking how it is suppose to work.

Thanks

**Comment by Tipue** [comment]
It's the number of results returned per page. If you've lost navigation you must've made changes to the script, and i would suggest re-installing.

**Comment by lenamtl** [comment]
Ok thanks a lot
