### ISSUE TITLE
how can i use other data from the json

### ISSUE THREAD

**Issue by moin5050** [Tipue/Tipue-Search#16]
hi , 
is it possible to add more data in the search results apart from the default (text, title ,tags , loc).
i wanted to use more like (name, location , city )

is it possible ..if yes how can i use them in search results..

thanks

**Comment by Tipue** [comment]
Not out of the box, I'm afraid. You'd have to rewrite some of the script.

**Comment by moin5050** [comment]
i just want to show data (adding them to search is not that imp).
can give a demo eg : if you can  . 
i am a newbie .

**Comment by Tipue** [comment]
No, you can't do that without writing a fair bit of code. Sorry.

**Comment by moin5050** [comment]
thanks.

**Comment by Tipue** [comment]
Sorry I couldn't be more help.
