### ISSUE TITLE
Tipue with a MySQL database. 

### ISSUE THREAD

**Issue by JacquesMarais** [Tipue/Tipue-Search#17]
Allowing this shouldn't be too hard. Just allow the user to set an option to get results from a PHP file then use a GET request to the file and use the JSON data as the results.

**Comment by JacquesMarais** [comment]
I could send you a pull request with the needed code as I am doing it with Tipue and MySQL on my own website.

**Comment by Tipue** [comment]
Thanks, that would very interesting.

**Comment by lenamtl** [comment]
+1

**Comment by Tipue** [comment]
You should use the Static mode JavaScript object rather than JSON, as Static mode is faster.
