### ISSUE TITLE
Option to narrow search with every new keyword entered

### ISSUE THREAD

**Issue by felixhayashi** [Tipue/Tipue-Search#22]
Hi, 

the more keywords I enter, the more hits I get. This is counter-intuitive. I would expect more keywords to narrow the search like google does it. Say I search for "network" and get 9 results and add a keyword "method" and now I would expect to only get results displayed that contain both words, however, now all pages that contain "method" are also added to the results and I get 14 results.

Is there an option for this? Thanks

-Felix

**Comment by Tipue** [comment]
This is normal behavior for site search engines. It returns all results containing the search terms, with the most highest scoring results first.
