### ISSUE TITLE
include original tags in generated markup as option

### ISSUE THREAD

**Issue by mcat** [Tipue/Tipue-Search#25]
It would be very handy if the original tags that are fed into the search are optionally returned back in the generated markup. For sites that have different content types this would be a good way to improve the usability of the serp page.

**Comment by Tipue** [comment]
Can you elaborate? I'm not sure I understand what you're after.

**Comment by benlwilliams** [comment]
I think @mcat might be trying to say that it would be nice if any tipue generated html tags could be custimized as a part of the options.

**Comment by Tipue** [comment]
That might be something to think about in a future release.
