### ISSUE TITLE
Different Search Results

### ISSUE THREAD

**Issue by tjgambs** [Tipue/Tipue-Search#29]
I am getting different search results when using firefox and google chrome. Is this normal?

**Comment by Tipue** [comment]
I take it you're using Live mode? In what way different?

**Comment by tjgambs** [comment]
Actually I am using static mode. I get the same results with every browser except google chrome. I am using tipue search to create a course search for my university. If you look up "acc" in google chrome you get, in this order, "acc 545, acc 100, acc 102, acc 250, acc 303."  In any other browser, when you look up "acc", you get "acc 100, acc 101, acc 102, acc 250, acc 303."

**Comment by Tipue** [comment]
It isn't something I've seen before. Are you declaring a document type definition (DTD) at the top of the page?

**Comment by tjgambs** [comment]
It is the same on your website for me. If you open http://www.tipue.com/search/demos/static/search.cgi?q=tipue in google chrome and firefox, the results are different (yes I know it is only one, but sometimes it is more than one). Could I be doing something wrong on my end? Thanks.

**Comment by Tipue** [comment]
No, I don't think it's anything you're doing. I'll look into this in the next couple of days and get back to you.
