### ISSUE TITLE
Specific section of the search word for the Search Description

### ISSUE THREAD

**Issue by omarjames13** [Tipue/Tipue-Search#31]
Im using Live Mode, is there a way that i can only show the specific section where the word occurs which can include word before the search word and the word after the search word. Hope you can help me in this matter.

**Comment by Tipue** [comment]
You can't, I'm afraid. This is coming in the next release, probably around late spring/early summer.

**Comment by omarjames13** [comment]
Thank you very much.. Looking forward on the next update.

**Comment by michael-milette** [comment]
Note: This has been fixed in Pull Request #39.
