### ISSUE TITLE
Keyboard accessibly and ARIA

### ISSUE THREAD

**Issue by Decrepidos** [Tipue/Tipue-Search#33]
Hi

I notice that the pagination on the results page is not keyboard accessible. Also it would be great if you added ARIA attributes to make it more accessible.

Thanks

Cheers
Decrepidos

**Comment by Tipue** [comment]
Thanks. I'll look into this for the next release.

**Comment by michael-milette** [comment]
Note: This has been fixed in Pull Request #39.
