### ISSUE TITLE
Apply word highlighting after text truncation

### ISSUE THREAD

**Issue by redihokuto** [Tipue/Tipue-Search#34]
In your code (v5.0, but also in previous versions) you apply a `<span class="h01> </span>` to each searched term. The snippet starts with `if (set.highlightTerms)`. Then, the descriptive text is truncated to fit desired word count `descriptiveWords`. It may happen to truncate right in the middle of the "span" with obvious inconsistent result on rendered page.

The _highlight_ piece of code should be moved after descriptive text truncation. 

I've done the modification on my own, but I'm not a JavaScript programmer even though I write code (predominantly in C) so it's better I don't push my mods on your repo.

**Comment by Tipue** [comment]
Thanks, but this has me foxed. Can you give me an example?

**Comment by redihokuto** [comment]
Sure!
'This is the text where the term text you entered is looked for'
1. highlighting is applied
'This is the <span class="h01">text</span> where the term <span class="h01">text</span> you entered is looked for'
2. Pretend you have limited the description to 9 space separated words. Truncation
'This is the <span class="h01">text</span> where the term <span...'

As you can see the result is not consistent.
My suggestion is to invert the 2 operations:
A. truncation
'This is the text where the term text you...'
B. Apply highlighting
'This is the <span class="h01">text</span> where the term <span class="h01">text</span> you...'

Always consistent. 
In general you need to apply description truncation to _bare_ text before any further decoration

**Comment by Tipue** [comment]
Ah! I understand now. I'll fix in the next release. Thanks.

**Comment by redihokuto** [comment]
Thanks for sharing! I discovered right now my post does not appear as I wrote it with all "span class". I fixed it, nevertheless you've got the point.
