### ISSUE TITLE
liveContent  value being ignored

### ISSUE THREAD

**Issue by benlwilliams** [Tipue/Tipue-Search#35]
I'm passing the following options into tipue search:
```
$('#tipue_search_input').tipuesearch({
	'mode': 'live',
	'show': 1000,
	'liveContent': '.main',
	'highlightEveryTerm': true
});
```
I also have 59 pages referenced in the `tipuesearch_set.js` file, like this:
```
var tipuesearch_pages = [
	"http://myurl.com/Directory/Filename1.html",
	"http://myurl.com/Directory/Filename2.html",
	/* and so on */
	"http://myurl.com/Directory/Filename59.html"
]
```
When the search runs, two problems occur. 

1. the `liveContent` field is being ignored. Everything is being searched on each page, even if it's outside of the `.main` div.
2. In the search results, it just shows the start of the content of each result, and not the search term in context of where it exists on the page.

**Comment by benlwilliams** [comment]
I don't very well understand the difference of liveContent and liveDescription but figured out if I gave both of them the same value, I got more of what I was expecting in the search results.  But I still wonder if there is any way to have the search results description show the words surrounding the search term, rather than just the first words found in the liveDescription element?

**Comment by Tipue** [comment]
Both liveContent and liveDescription are very dependent on well-formed HTML, which is why we recommend Static mode. See the docs at http://www.tipue.com/search/docs/?d=5

The search terms in context is coming in the next release.

**Comment by benlwilliams** [comment]
Thanks.  Looking forward to next release with in-context results.
