### ISSUE TITLE
whitespace error?

### ISSUE THREAD

**Issue by mclearc** [Tipue/Tipue-Search#36]
all of my search results have `code{white-space: pre;}` in the beginning of the first line of every content entry (i.e. after the title and link for each entry). Any idea what I'm doing wrong? I'm using tipue-search 5.0 with json mode and pelican static generator.

**Comment by Tipue** [comment]
That isn't something I've seen before. Is it in your json data file?

**Comment by mclearc** [comment]
It is. It is the first entry in the "text" area in fact: `"text":"code{white-space: pre;}`

**Comment by Tipue** [comment]
How are you creating your json data file?

**Comment by mclearc** [comment]
If I'm right to assume that the jason data file is the "tipuesearch_content.json" file then it is created by pelican (a static site generator) based on this snippet from a jinja template:

````
{% block scripts %}
{% if 'assets' in PLUGINS %}
{% include 'include/minify_tipuesearch.html' with context %}
{% else %}
    <script type="text/javascript" src="{{ SITEURL }}/{{ THEME_STATIC_DIR }}/tipuesearch/tipuesearch_content.js"></script>
    <script type="text/javascript" src="{{ SITEURL }}/{{ THEME_STATIC_DIR }}/tipuesearch/tipuesearch_set.js"></script>
    <script type="text/javascript" src="{{ SITEURL }}/{{ THEME_STATIC_DIR }}/tipuesearch/tipuesearch.min.js"></script>
    {% endif %}
    <script>
    $(document).ready(function() {
      $('#tipue_search_input').tipuesearch({
        'mode' : 'json',
        'show': 10,
        'newWindow': false,
        'contentLocation': 'tipuesearch_content.json'
      });
    });
    </script>
{% endblock %}
````

**Comment by Tipue** [comment]
I take it Tipue Search is bundled with Pelican, and I think you'll have to get in touch with them. Sorry.

**Comment by mclearc** [comment]
Ah. Well it's a  [plugin](https://github.com/getpelican/pelican-plugins/tree/master/tipue_search), not baked into the generator. But since I take it that nothing in tipuesearch 5 should have caused this I'll check with the plugin maker. Thanks.

**Comment by Tipue** [comment]
No problem. Good luck.
