### ISSUE TITLE
Displayed content doesn't show keyword if word is in the title

### ISSUE THREAD

**Issue by michael-milette** [Tipue/Tipue-Search#37]
I recently came across Tipue Search and love it. I found it easy to customize for use in other languages too.

*What is happening*

The problem I noticed is that, if a keyword is part of the page title, the script doesn't even try to display relevant text in the content section.

Here is a screenshot:
![image](https://cloud.githubusercontent.com/assets/3808579/16105561/78ce4892-3359-11e6-82bc-986e97e5f736.png)

*What I expected*

1. If the search term is found in the title, it should be highlighted.
2. Even if the search term is found in the title, the script should display a snippet of the content that is relevant to the search - just as if the search term had not been found in the page title.

I have to deliver my project next week. Any chance you could help me resolve this issue before then?

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
By the way, I am using Version 5.0 that I downloaded from here yesterday.

**Comment by Tipue** [comment]
I can't do anything for next week, but I will look at your comments for the next release.

**Comment by michael-milette** [comment]
Unfortunately I will no longer ever have access to my project after the end of next week. However I appreciate you responding. I'll have to see if I can figure it out myself.

I noticed in one of your responses that you intended to put out the release in Late Sprint or Early Summer. Can you give an update on this?

**Comment by Tipue** [comment]
Other things have got in the way and I'm expecting the next release coming probably around mid-summer.

**Comment by michael-milette** [comment]
Note: This issue has been resolved in Pull Request #39.
