### ISSUE TITLE
Allow live search

### ISSUE THREAD

**Issue by noplay** [Tipue/Tipue-Search#38]
Hi,

Thanks for this project.

Actually search is only made when you hit enter:
https://github.com/Tipue/Tipue-Search/blob/master/tipuesearch/tipuesearch.js#L108

But it could be interesting to allow the search as you type.

What do you think about that?

**Comment by Tipue** [comment]
I'm not sure how it would work, but it's would be interesting to try. I'll look at this for the next release. Thanks.

**Comment by noplay** [comment]
Actually by commenting the if in the keyup I got it working. But probably need some tuning.

**Comment by Tipue** [comment]
Yes, it would need some polishing. Nice idea, thanks.
