### ISSUE TITLE
make page fetching asynchronous

### ISSUE THREAD

**Issue by afeld** [Tipue/Tipue-Search#40]
Just came across this plugin—really like the spirit of it, but was looking at the performance, and noticed that in Live mode, the requests for the pages happen serially:

![screen shot 2016-08-04 at 1 22 42 am](https://cloud.githubusercontent.com/assets/86842/17391162/f81cbdf0-59e1-11e6-8277-18c1808a7e10.png)

The performance could be _dramatically_ improved if the requests were performed asynchronously, and I think that conversion would be relatively straightforward. Thanks!

**Comment by afeld** [comment]
So...no? 😇

**Comment by Tipue** [comment]
I'm currently working on a new release, so maybe. :-)
