### ISSUE TITLE
Accent folding feature for various languages

### ISSUE THREAD

**Issue by miljkovicmisa** [Tipue/Tipue-Search#43]
Hello, I have written to you before via email about this request but it seems more appropriate to comment here as well.

It would be really nice to implement an accent folding option for languages that have accents like French or Greek. You can see [this article on ALA](http://alistapart.com/article/accent-folding-for-auto-complete) where the author talks heavily about this topic and how to implement it on autocomplete.

Thanks in advance and keep up the hard work!

**Comment by Tipue** [comment]
Thanks. Work on the next release is underway and I'll look into this soon.
