### ISSUE TITLE
Tipue-Search in a single page application

### ISSUE THREAD

**Issue by dsmithdewarcom** [Tipue/Tipue-Search#47]
Hi,
I just started looking at Tipue-Search and it looks really powerful, yet lightweight in terms of code. Well done!

I would like to try and get this working in an HTML5 single page application that uses dynamic content loading based on hashed urls, and I've got a few questions:

First, can I use the hashes for the live mode list of tipuesearch_pages, e.g. ["#first","#second","#third"].

Secondly, can I get the search results to load into a div on the same page, instead of a separate page? So presumably not `<form action="myurl">`.

And on an unrelated note, does Tipue-Search work with jquery-1.11.1? I'm using it instead of a newer version in my app for compatibility with latest stable jquery-mobile (1.4.5).

Thanks for any help you are able to provide!

**Comment by Tipue** [comment]
No, I don't think hashes will work in Live mode. Static mode is probably the way to go here.

Yup, you can use the same page. Just start with the results page rather than a search page.

No, Tipue Search is jQuery 2.x and above.

Cheers,
Steve

**Comment by dsmithdewarcom** [comment]
Thanks for the speedy response. It appears that jq-mobile will work with the same (newer) version of jquery, at least for the very limited mobile functions I need (just swiping).

I got the search results on the same (single) page, will try static mode. Thanks again.

**Comment by Tipue** [comment]
No worries. Good hunting.
