### ISSUE TITLE
Concatenate tipuesearch javascripts?

### ISSUE THREAD

**Issue by dsmithdewarcom** [Tipue/Tipue-Search#49]
Hi,
I'm back and I got tipue search working pretty good in my single-page app (and thanks for providing this awesome tool, by the way!)

I would like to streamline the loading of javascripts in my app a bit, and I was able to combine tipuesearch.js and tipuesearch_set.js.

I was considering switching from 'static' to 'JSON' mode, except your documentation says static is the faster (not sure why this would be, but I'll take your word for it).

Would I be able to paste the "pages" array in tipuesearch_content.js into the concatenated scripts (as described), and if so how would I need to reference it in the main tipuesearch.js code?

Thanks for any help.

David Smith

**Comment by Tipue** [comment]
You would have to put it at the top of the script. It should work.
