### ISSUE TITLE
How to impliment ajax search using tipue search?

### ISSUE THREAD

**Issue by wondie** [Tipue/Tipue-Search#55]
Nice plugin! I wanted to prevent the page from loading and still show search result in the same page. Is it possible?

**Comment by Tipue** [comment]
Just search from the results page, which includes a search box.

**Comment by wondie** [comment]
I wanted to embed the search box in another page so that I show the search result container. Something that hides and shows.

**Comment by Tipue** [comment]
I'm not sure that's possible, but perhaps someone else has an idea?

**Comment by wondie** [comment]
I think it is possible. It is basally adding an option to where the search result should appear, in a div or in a different search page. The div might have a close button so that users can hide it.  
For instance, in this app http://apps.rcmrd.org/waterquality/index.php if you click on Multiple Map Search --> Custom Search, it shows a div.

**Comment by Tipue** [comment]
The results display in a div, <div id="tipue_search_content"></div>. You could use this.

**Comment by wondie** [comment]
Use which?

**Comment by Tipue** [comment]
There's a div that displays the results, with the id "tipue_search_content". See http://www.tipue.com/search/docs/?d=1

**Comment by wondie** [comment]
That is cool. However, how can I prevent the page from reloading when the form is submitted but still get the result in "tipue_search_content"?

**Comment by Tipue** [comment]
Sorry, beyond that I can't help.

**Comment by davidjb** [comment]
@wondie By default, Tipue Search listens for the keyup event for your enter/return key and performs the search, filling the `#tipue_search_content` element with results.  However, the browser also submits your search `<form>` at the same time  so this is what you're probably seeing when the page reloads.

To get what you want, you need to prevent the browser from submitting the search form.  You'll need to adjust the jQuery selector below to target your search form (or add `id="search_form"` to your form's HTML):

```jquery
    $('#search_form').on('submit', function(event) {
        event.preventDefault()
    })
```

@Tipue This appears to be a situation that could be improved.  As it currently stands, both the JS-based search and form submission happen simultaneously, meaning the JS search processing gets wasted as the browser "submits" the form, also inefficient as the page didn't need a reload to see the results.  Could/should this plugin prevent form submission by default? It feels like this should be the default, and then provide the option to allow for search form submission if a user is generating dynamic search results during HTTP requests.
