### ISSUE TITLE
Including bookmarks in the Results page

### ISSUE THREAD

**Issue by linuxlite** [Tipue/Tipue-Search#56]
Would you consider including a feature that ensure that it also shows bookmarks in the search results?

eg. the search word is 'bios' the results page shows:

Help Manual - Install
install.html#bios
... Mounted Drives - Advanced Users No USB Boot option in the BIOS? Preparing your Computer Removing a User Resetting your Password Securely Erasing ...

I would be more than happy to contribute financially for this feature.

**Comment by Tipue** [comment]
Talk to us by email at post@tipue.com
