### ISSUE TITLE
Search terms don't like + character

### ISSUE THREAD

**Issue by chasnz** [Tipue/Tipue-Search#57]
Passing search terms that include the + character throws a JavaScript error. The regular expression fails in getTipueSearch function.
Error response = Uncaught SyntaxError: Invalid regular expression: /\b+integrity\b/: Nothing to repeat
Suggest addition of
    d = d.replace(/\+/, '');
after line 144 in tipuesearch.js

**Comment by Tipue** [comment]
Thanks. I'll include this in the next release, due in a couple of weeks.
