### ISSUE TITLE
liveContent functionality misunderstanding?

### ISSUE THREAD

**Issue by squareclouds** [Tipue/Tipue-Search#62]
hi guys,

i love tipue, since i currently use a small cms with no database (pulseCMS). a client needs a search function thou, and that's where tipue will be of great help!

i have a problem thou. i am testing the tool live on my page. here i have a references page listing all my projects and these projects have no extra page! so they are rendered only in the references section:

https://www.squareclouds-design.de/referenzen

(acutally they do have pages of their own, but i dont use the project-pages, since my content is really tight packed, so there is only the overview in "references" – and only this page is listed in the tipue_set).

this is very special feature, but is there a way to create a result-link for every match tipue finds? so if i am currently looking in references, every time tipue finds the word "website" a new result item gets added, and not only one time for the whole references page. im guessing almost no one will need this, but i was just wondering.

this is my search page with tipue
https://www.squareclouds-design.de/go

the second thing is (and now to the actual subject of this post), if you search for "home" tipue gives back javascript results! i guess this is because at some points i insert javascript into the body (sadly no workaround because of the cms). i tried using 'liveContent' to filter the javascript out, looking only in the content area and i think it works, but only using it with 'liveDescription' (for example "reference-title"). i dont want to use a specific 'liveDescription' (i want the preview with context previous and after the matched word) so it is a bit problematic that tipue does his job a bit too well looking into javascript as well. can i somehow skip the <script>-tags?

if i spend a couple of hours i am sure i can find everything out, but i tought maybe you can help me with these issues a lot faster :)

<img width="687" alt="bildschirmfoto 2017-08-07 um 17 58 53" src="https://user-images.githubusercontent.com/9073054/29034937-381b8d3e-7b9a-11e7-8c74-a03d0ec34a2c.png">

**Comment by Tipue** [comment]
Rather than use Live mode you might be better off indexing your site using Beaty at http://www.tipue.com/beaty. Though this is in early beta at the moment, it will probably both your issues.

**Comment by squareclouds** [comment]
thanks for your reply! sadly it is not working :/ any advice?

![bildschirmfoto 2017-08-07 um 20 16 15](https://user-images.githubusercontent.com/9073054/29040052-f34b2dc2-7bad-11e7-98e5-c52a02a6d98d.png)

**Comment by squareclouds** [comment]
it was indeed the https, with http it works fine.. i turned off all rewrites in my htaccess, so it appears to be a problem with https itself and not the htaccess

**Comment by Tipue** [comment]
It follows links. Do you have any links to content on the home page?

**Comment by squareclouds** [comment]
yes, but the navigation is created with php by the cms, so that may be the problem? i think live mode works just fine for the project that is coming, and i actually dont really need it for my website. if problems arise i will try to implement a small php json-writer for pulseCMS so the json set gets updated everytime a page is updated/saved. thanks for your help!!

**Comment by Tipue** [comment]
Shame I couldn't help more, thanks.
