### ISSUE TITLE
Does not index entire site

### ISSUE THREAD

**Issue by TristianK3604** [Tipue/Tipue-Search#68]
According to the documents, it says that you need to include all the folder URLs to your site. Well, I only want the root indexed by Tipue, so I only put that in, and it seems all it shows in the search results is the home page. Nothing else. Do I need to include the URLs to the HTML files too or something?

**Comment by Tipue** [comment]
You have to include all the pages you want to be indexed.

**Comment by TristianK3604** [comment]
Oh, alright. Now, though, I did that, it works now for one of my sites, but on my other one, it's just infinitely showing a loading sign.
